name: BankApp CI

on:
  push:
    branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
        
      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" $GITHUB_PATH

      - name: Begin SonarCloud Analysis
        run: dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /o:"${{ secrets.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.cobertura.xml"

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests with code coverage
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: '**/TestResults/*.xml'

      - name: End SonarCloud Analysis
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}